logging.level.org.springframework=TRACE
logging.level.com=TRACE

spring.mvc.view.prefix=/WEB-INF/view/
spring.mvc.view.suffix=.jsp
server.servlet.context-path=/shop
server.error.whitelabel.enabled=false


spring.resources.static-locations=file:/C:/Users/chris/pictures/onlineshop

spring.datasource.url=jdbc:mysql://localhost:3306/funtestapp?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
#spring.datasource.password=sesame
spring.datasource.password=admin
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.security.user.name=chrisenoch
#spring.security.user.password=sesame

#server.servlet.session.timeout=60

# Hibernate configuration.
hibernate.show_sql=true
hibernate.hbm2ddl.auto=update
hibernate.dialect=org.hibernate.dialect.MySQL5Dialect
# Package to scan.
packagesToScan= com.chrisenoch.onlineshop



STRIPE_PUBLIC_KEY=pk_test_51HMyzRDI9n6vlhglp6G8W0alxBlu7Wne8K7MpBBNjkbj9m1rLeUfPZMQE83Un5E8enLri1MSiiG380Rl7x2RNuPD00bydJMb79
STRIPE_SECRET_KEY=sk_test_51HMyzRDI9n6vlhgluCXpeSCPmUq62vR65Tgm6Kpy5IDAg9HmFW6w9hFtNIbfRyYON3sGDY7LePmjz7nieZeiuPew00Dn4F8qf2

spring.profiles.active=hibernate


